name: Build and Publish to PyPI (Multi-Python)

on:
  push:
    tags:
      - 'v*.*.*'  # add tag to trigger the workflow

jobs:
  build-and-publish:
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NodeRAG-dist-py${{ matrix.python-version }}
          path: dist/*

      - name: Upload to PyPI (only on Python 3.10)
        if: matrix.python-version == '3.10'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*

