name: Build Python Package

on:
  push:
    tags:
      - 'v*.*.*'  # add tag to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # choose one system to build, the result is applicable to all platforms
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip build

      - name: Build package
        run: |
          python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: NodeRAG-dist
          path: dist/*
